name: base-test-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - pandas==1.0
  - numpy==1.16
  - scipy==1.1
  - scikit-learn==0.23
  - seaborn==0.11
  - plotly==4.0
  - pytest>=6.0.0
  - pytest-cov>=2.6.0
  - pytest-notebook>=0.6
  - mock>=4.0
